/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "tertiary-container": "#a36700",
        "on-secondary-container": "#00714d",
        "tertiary-fixed-dim": "#ffb95f",
        "outline-variant": "#bdc9c5",
        "surface-bright": "#faf8ff",
        "on-tertiary-container": "#fffaf9",
        "tertiary": "#815100",
        "error-container": "#ffdad6",
        "surface": "#faf8ff",
        "secondary-container": "#6cf8bb",
        "secondary-fixed": "#6ffbbe",
        "primary-container": "#0d8275",
        "surface-tint": "#006b5f",
        "secondary-fixed-dim": "#4edea3",
        "on-primary-container": "#edfffa",
        "on-secondary": "#ffffff",
        "surface-container-highest": "#dae2fd",
        "surface-container-high": "#e2e7ff",
        "surface-dim": "#d2d9f4",
        "primary-fixed-dim": "#77d7c8",
        "surface-container-lowest": "#ffffff",
        "on-tertiary": "#ffffff",
        "surface-container": "#eaedff",
        "background": "#faf8ff",
        "on-primary-fixed-variant": "#005048",
        "on-background": "#131b2e",
        "surface-container-low": "#f2f3ff",
        "inverse-on-surface": "#eef0ff",
        "on-error-container": "#93000a",
        "inverse-primary": "#77d7c8",
        "error": "#ba1a1a",
        "primary-fixed": "#94f4e3",
        "on-surface": "#131b2e",
        "on-primary-fixed": "#00201c",
        "on-secondary-fixed-variant": "#005236",
        "on-secondary-fixed": "#002113",
        "on-error": "#ffffff",
        "on-primary": "#ffffff",
        "surface-variant": "#dae2fd",
        "on-surface-variant": "#3e4946",
        "on-tertiary-fixed-variant": "#653e00",
        "tertiary-fixed": "#ffddb8",
        "secondary": "#006c49",
        "on-tertiary-fixed": "#2a1700",
        "inverse-surface": "#283044",
        "outline": "#6e7a77",
        "primary": "#00675c"
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
      spacing: {
        "space-lg": "1.5rem",
        "space-xs": "0.25rem",
        "gutter-desktop": "1.5rem",
        "space-xl": "2rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "margin-tablet": "1.5rem",
        "margin-desktop": "2.5rem",
        "gutter": "1rem",
        "margin": "1rem",
        "space-2xl": "3rem"
      },
      fontFamily: {
        "price-lg": ["Plus Jakarta Sans", "sans-serif"],
        "headline-xl": ["Plus Jakarta Sans", "sans-serif"],
        "label-lg": ["Inter", "sans-serif"],
        "label-sm": ["Inter", "sans-serif"],
        "headline-md": ["Plus Jakarta Sans", "sans-serif"],
        "headline-lg": ["Plus Jakarta Sans", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-lg-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "label-md": ["Inter", "sans-serif"],
        "headline-sm": ["Plus Jakarta Sans", "sans-serif"],
        "body-sm": ["Inter", "sans-serif"],
        "headline-xl-mobile": ["Plus Jakarta Sans", "sans-serif"],
        "price-md": ["Plus Jakarta Sans", "sans-serif"],
        "body-md": ["Inter", "sans-serif"]
      },
      fontSize: {
        "price-lg": ["22px", { "lineHeight": "28px", "fontWeight": "700" }],
        "headline-xl": ["36px", { "lineHeight": "44px", "fontWeight": "700" }],
        "label-lg": ["14px", { "lineHeight": "20px", "letterSpacing": "0.01em", "fontWeight": "600" }],
        "label-sm": ["11px", { "lineHeight": "14px", "letterSpacing": "0.04em", "fontWeight": "700" }],
        "headline-md": ["20px", { "lineHeight": "28px", "fontWeight": "600" }],
        "headline-lg": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "body-lg": ["16px", { "lineHeight": "26px", "fontWeight": "400" }],
        "headline-lg-mobile": ["22px", { "lineHeight": "28px", "fontWeight": "600" }],
        "label-md": ["12px", { "lineHeight": "16px", "letterSpacing": "0.02em", "fontWeight": "600" }],
        "headline-sm": ["16px", { "lineHeight": "24px", "fontWeight": "600" }],
        "body-sm": ["12px", { "lineHeight": "18px", "fontWeight": "400" }],
        "headline-xl-mobile": ["28px", { "lineHeight": "36px", "fontWeight": "700" }],
        "price-md": ["16px", { "lineHeight": "22px", "fontWeight": "700" }],
        "body-md": ["14px", { "lineHeight": "22px", "fontWeight": "400" }]
      }
    }
  }
}
