export const MOCK_MEDICINES = [
  {
    id: 'm1',
    name: 'Napa Extra',
    genericName: 'Paracetamol 500mg + Caffeine 65mg',
    manufacturer: 'Beximco Pharmaceuticals',
    isOtc: true,
    form: 'Tablet',
    packSize: '12',
    price: 36,
    originalPrice: 40,
    discount: 10,
    unit: 'Strip',
    rating: 4.9,
    category: 'fever',
    inStock: true,
    description: 'Napa Extra is a combination of Paracetamol and Caffeine. Paracetamol is a fast-acting analgesic and antipyretic. Caffeine acts to enhance the pain-relieving effect of Paracetamol.',
    indications: ['Headache', 'Migraine', 'Toothache', 'Neuralgia', 'Feverishness', 'Period pain', 'Sore throat'],
    howToUse: 'Adults: 1-2 tablets every 4-6 hours as needed. Do not exceed 8 tablets in 24 hours. Swallow with a glass of water.',
    safetyInfo: 'Do not take with any other paracetamol-containing products. Consult your doctor if symptoms persist for more than 3 days. Avoid excessive caffeine intake (e.g. coffee, tea) while taking this product.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBf8QgTeefksxI4jClTU-PDm5OQGVzeqSviWKknUQk2hH5iwHllB_t5r66_8hNU2NhKf8S2XjuM3BefCKC0GCSUX9L8XVd-EYMaJ8JwU5NXz9caJugnojSHHG0KPp2KiwJ7iZ09un8E53fvU7vNufU9X3dKh4YjZkZJWIb_m6hwU39LDq6QaRO_pV86Q22FbrHsX90z9msuDxPMvrJera8fBrFq3NY17SYtrnRNfvCihcC4rvsIMXUk'
  },
  {
    id: 'm2',
    name: 'Maxpro 20',
    genericName: 'Esomeprazole Magnesium 20mg',
    manufacturer: 'Square Pharmaceuticals',
    isOtc: true,
    form: 'Capsule',
    packSize: '10',
    price: 70,
    originalPrice: 70,
    discount: 0,
    unit: 'Strip',
    rating: 4.8,
    category: 'gastric',
    inStock: true,
    description: 'Maxpro is a proton pump inhibitor (PPI) that suppresses gastric acid secretion by specific inhibition of the H+/K+-ATPase in the gastric parietal cell.',
    indications: ['Gastroesophageal reflux disease (GERD)', 'Erosive esophagitis', 'Zollinger-Ellison syndrome', 'Peptic ulcer disease'],
    howToUse: 'Take 1 capsule daily before a meal, preferably in the morning. Swallow whole, do not chew or crush.',
    safetyInfo: 'Inform your doctor if you have severe liver disease. Long-term use may increase the risk of bone fractures and Vitamin B12 deficiency.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBQj3-lgFODFI5vzOkC4eapSi8EnH7Nb4M5OUcW69JUvPSPCmf7nRyL_hqSX_NHnikYAurvlLX6Qf6_zLn8f3f222UZya3RloN3579elgODymD0d9vZgOTp3MLu2R-Ma2o2APRT4kKjiZDY_9mQeD9hsxRUx6wr3MBuFfywXsSnyj_KkC_P96CwTtgWp_Nyxq05T9drSiozNdLu9jMasnthMq5A0Jn6QBebJ3jrIgQQn0miKJb-c8Vs'
  },
  {
    id: 'm3',
    name: 'Monas 10',
    genericName: 'Montelukast Sodium 10mg',
    manufacturer: 'The ACME Laboratories',
    isOtc: false,
    form: 'Tablet',
    packSize: '10',
    price: 175,
    originalPrice: 185,
    discount: 5,
    unit: 'Strip',
    rating: 4.9,
    category: 'respiratory',
    inStock: true,
    description: 'Monas acts as a leukotriene receptor antagonist. It blocks the action of leukotrienes, which cause narrowing and swelling of airways in the lungs.',
    indications: ['Prophylaxis and chronic treatment of asthma', 'Relief of symptoms of allergic rhinitis (seasonal and perennial)'],
    howToUse: 'Adults: 1 tablet daily in the evening. For allergic rhinitis, the time of administration may be individualized.',
    safetyInfo: 'Not intended for relief of acute asthma attacks. May cause neuropsychiatric events in rare cases (e.g., agitation, sleep disturbances).',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuBeDFEaSDObBgWG7mxSHvgK6s8c859NxIdvWWrvxYar3WjA6_HnEcYy5GCRXaBbm81KYRHKnyjub6Kg2ltQjdV2Wm0x5-GKDthSatrXU1PkqH0MdjBlDFO_op3DKMEBAOWE7EDbmqStL4_aYS9MASteW9zDSlOus4G3KLEdl8ShmqtgRV8mJKJjG81UEA7Ge4Tde0CR81FCQv5fcVDMyJXAUQpe_WnxatKFDnpnsaBZ-LqhkoUa0TGg'
  },
  {
    id: 'm4',
    name: 'Savlon Antiseptic',
    genericName: 'Chlorhexidine Gluconate + Cetrimide',
    manufacturer: 'ACI Limited',
    isOtc: true,
    form: 'Liquid',
    packSize: '1',
    price: 110,
    originalPrice: 110,
    discount: 0,
    unit: 'Bottle',
    rating: 4.7,
    category: 'hygiene',
    inStock: true,
    description: 'Savlon Liquid Antiseptic contains two active ingredients: Chlorhexidine Gluconate and Cetrimide. It is used for first aid, personal hygiene, and general household cleaning.',
    indications: ['First aid (cuts, grazes, bites)', 'Personal hygiene (bath, dandruff)', 'Household cleaning'],
    howToUse: 'Dilute before use. For first aid: 1 capful in a glass of water. For bathing: 1-2 capfuls in bath water.',
    safetyInfo: 'For external use only. Avoid contact with eyes and ears. Keep out of reach of children.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuD7KCYmVX6AzMCtddeVWh3n0xdSdT8jLrl6UgD_9g_7-4IsryUiVmVIsdvCIxXQQGKTaxxpC8gOuIqdwggupWLEU4iFuIpl40eotCJRa6VbmhbqWvy14BLpxcDn3rB_1NSeEG7s7LldxTTz8DzKndBFIreIHBMorxMRb9XzkSpPjB_09irQd93nNPc7HPuts5prUaLYDHIgcNtm5o3FZzIeuCDVVl6RXB2ntmyvAMb3R0cnRA_JCZL9'
  },
  {
    id: 'm5',
    name: 'Accu-Chek Instant',
    genericName: 'Blood Glucose Meter Kit',
    manufacturer: 'Roche Diabetes Care',
    isOtc: true,
    form: 'Device',
    packSize: '1',
    price: 1650,
    originalPrice: 1800,
    discount: 8,
    unit: 'Kit',
    rating: 4.9,
    category: 'devices',
    inStock: false,
    description: 'Accu-Chek Instant meter makes testing blood sugar easy. It features a target range indicator that gives visual reassurance if your blood glucose values are high, low or in-range.',
    indications: ['Blood glucose monitoring for diabetics'],
    howToUse: 'Insert a test strip, apply a small blood drop to the yellow edge of the test strip, and read the result in less than 4 seconds.',
    safetyInfo: 'Store test strips in their original vial. Do not use expired test strips. Keep the meter clean and away from extreme temperatures.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAlQKws2uu6N05JRF-qHVdhM9WY_djUwbSdt92sCwqU7XEY---tMRMHM5LS8f7ROwnQ7jHbQrcZsLcuUJX79Rf5L1WW3E0q6KesxEEO8sZZa9FoWW7LzKQpdMZDGIr0g2P0IhT0bvtT42hC1yJehYJa8W2VPSkfjnKdxfiT2DxAa3bC2RZXtjIrx8mu6SPzQMrVrEiH7V2zoyR_IiglKkdnpc3PDUSopc6bvEts7OFer-ZueeT_cdry'
  },
  {
    id: 'm6',
    name: 'Seclo 20',
    genericName: 'Omeprazole BP 20mg',
    manufacturer: 'Square Pharmaceuticals',
    isOtc: true,
    form: 'Capsule',
    packSize: '10',
    price: 60,
    originalPrice: 60,
    discount: 0,
    unit: 'Strip',
    rating: 4.7,
    category: 'gastric',
    inStock: true,
    description: 'Seclo is a proton pump inhibitor used for the treatment of conditions caused by excess stomach acid.',
    indications: ['Gastric ulcer', 'Duodenal ulcer', 'GERD', 'Zollinger-Ellison syndrome'],
    howToUse: 'Take 1 capsule 30 minutes before breakfast.',
    safetyInfo: 'Avoid in patients with known hypersensitivity to omeprazole. May mask symptoms of gastric cancer.',
    image: 'https://lh3.googleusercontent.com/aida-public/AB6AXuAuRLT6bze253pAy47pamU_u64wCAz50JPJx-uWBuzfrGz75RZq24XX2Sb7FSbGrqiWbhgGR1Mz9RPCZv1pkT2bcY_fVBbRU5hbIA0eOvsQlWWVhzN4aOzc8AUwojXuBvGYVycyTNZV8pJ8i5MBXAdF_-xhNz82wcDHGaEbPrGmt6Gvrxx0YmW_vC3UwRAr2A4awkSKVvBRSM-MMug1pZVbhdmTzPpPGEN6W0C5zQtmvlEuNHxmXnF3'
  }
];
